### ISSUE TITLE
PiT: project in dev-mode does not work in gitpod 

### ISSUE THREAD

**Issue by manolo** [vaadin/base-starter-flow-quarkus#11]
checking out the project in [gitpod](https://gitpod.io/#https://github.com/vaadin/base-starter-flow-quarkus), it fails to start in dev mode (`mvn quarkus:dev`). Though, checking out the quarkus official [getting-started project](https://quarkus.io/guides/getting-started),  it worked
```
2021-10-21 06:22:52,617 ERROR [io.qua.run.boo.StartupActionImpl] (Quarkus Main Thread) Error running Quarkus: java.lang.reflect.InvocationTargetException
...
Caused by: java.lang.annotation.AnnotationTypeMismatchException: Incorrectly typed data found for annotation element public abstract java.lang.String[] com.vaadin.flow.router.Route.value() (Found data of type class java.lang.String[])
        at java.base/sun.reflect.annotation.AnnotationTypeMismatchExceptionProxy.generateException(AnnotationTypeMismatchExceptionProxy.java:57)
        at java.base/sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:86)
        at com.sun.proxy.$Proxy30.value(Unknown Source)
        at com.vaadin.flow.router.internal.RouteUtil.getAliasObjects(RouteUtil.java:371)
```

**Comment by mshabarov** [comment]
Tried with `22.0.0.beta1`, it starts fine in gitpod.
Could you please recheck @manolo ?

**Comment by manolo** [comment]
tried with 22.0.0.beta1 and 22.0.0 and don't work.

**Comment by manolo** [comment]
22.0.2 seems not failing, the problem is about ports now, probably is a gitpod issue. Closing this right now.
