### ISSUE TITLE
PiT: gradle branch does not work 

### ISSUE THREAD

**Issue by manolo** [vaadin/base-starter-flow-quarkus#12]
### 21.0.0
- Using `vaadinVersion=21.0.0` version and running dev or production modes raises an NPE:
```
     2021-10-21 11:00:03,422 ERROR [io.und.req.io] (executor-thread-0) Exception handling request 994a1511-f952-48e8-a987-f99107ae1572-1 to /: java.lang.NullPointerException: Cannot invoke "com.vaadin.flow.server.VaadinService.getContext()" because "service" is null
        at com.vaadin.flow.internal.DevModeHandlerManager.getDevModeHandler(DevModeHandlerManager.java:87)
```
### 22.0.0.alpha8
- Using PiT  `vaadinVersion=22.0.0.alpha8`  version, does not find the artifacts:
```
   Plugin [id: 'com.vaadin', version: '22.0.0.alpha8'] was not found in any of the following sources:
   - Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
   - Plugin Repositories (could not resolve plugin artifact 'com.vaadin:com.vaadin.gradle.plugin:22.0.0.alpha8')
      Searched in the following repositories:
      MavenRepo
      Gradle Central Plugin Repository
```  
- Deploying the platform artifact in my local by running `./gradlew build publishToMavenLocal` in platform `22.0.0.alpha8`, and adding `mavenLocal()` to the `settings.gradle` file, and running the app in devmode `sh ./gradlew -Pvaadin.productionMode` app starts but fail with the same NPE above:
```
   2021-10-21 11:39:10,980 ERROR [io.und.req.io] (executor-thread-0) Exception handling request 6e88f1c6-0b4b-4ca5-8b92-5875d7c9298f-1 to /: java.lang.NullPointerException
        at com.vaadin.flow.internal.DevModeHandlerManager.getDevModeHandler(DevModeHandlerManager.java:77)
```
- But running in prod mode, it does not compiles `sh ./gradlew -Pvaadin.productionMode`:
```
> Task :vaadinBuildFrontend FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':vaadinBuildFrontend'.
> com.vaadin.flow.server.ExecutionFailedException: Error occured during goal execution: './build/flow-frontend/form' is not a valid version!Please run Maven with the -e switch (or Gradle with the --stacktrace switch), to learn the full stack trace.
```

**Comment by mshabarov** [comment]
Closed, since all the issues have been addressed.
