### ISSUE TITLE
quarkus-spring-data-jpa not working

### ISSUE THREAD

**Issue by lamemind-ud** [vaadin/base-starter-flow-quarkus#20]
# Description of the Bug

Hello,
I cloned this repository and tried to integrate some functions, but I'm stuck with database access.

# What i want to do
I'd like to use Spring repositories (`org.springframework.data.repository.*`) just like I already do in other Quarkus projects, throught the `quarkus-spring-data-jpa` extension.

# Stack trace 
**java.lang.IllegalArgumentException: Producer method return type not found in index: org.springframework.boot.autoconfigure.web.servlet.WebMvcRegistrations**

~~~
$ .\mvnw
[..]

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running it.ufficiodiscount.ExampleResourceTest
Downloading from vaadin-prereleases: https://maven.vaadin.com/vaadin-prereleases/org/webjars/npm/mobile-drag-drop/maven-metadata.xml
2022-02-20 17:53:05,142 WARN  [io.qua.hib.orm.dep.HibernateOrmProcessor] (build-25) Could not find a suitable persistence unit for model classes:
        - io.quarkus.hibernate.orm.panache.PanacheEntity
        - io.quarkus.hibernate.orm.panache.PanacheEntityBase
2022-02-20 17:53:05,344 WARN  [io.qua.arc.pro.BeanArchives] (build-25) Failed to index org.springframework.boot.autoconfigure.web.servlet.WebMvcRegistrations: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: TEST@6686
3941
2022-02-20 17:53:05,345 INFO  [io.qua.arc.pro.IndexClassLookupUtils] (build-25) Class for name: org.springframework.boot.autoconfigure.web.servlet.WebMvcRegistrations was not found in Jandex index. Please ensure the class is part of the index.
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.099 s <<< FAILURE! - in it.ufficiodiscount.ExampleResourceTest
[ERROR] it.ufficiodiscount.ExampleResourceTest.testHelloEndpoint  Time elapsed: 0.006 s  <<< ERROR!
java.lang.RuntimeException:
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#registerBeans threw an exception: java.lang.IllegalArgumentException: Producer method return type not found in index: org.springframework.boot.autoconfigure.web.servlet.WebMvcRegist
rations
        at io.quarkus.arc.processor.Types.getProducerMethodTypeClosure(Types.java:245)
        at io.quarkus.arc.processor.Beans.createProducerMethod(Beans.java:236)
        at io.quarkus.arc.processor.BeanDeployment.findBeans(BeanDeployment.java:1020)
        at io.quarkus.arc.processor.BeanDeployment.registerBeans(BeanDeployment.java:233)
        at io.quarkus.arc.processor.BeanProcessor.registerBeans(BeanProcessor.java:120)
        at io.quarkus.arc.deployment.ArcProcessor.registerBeans(ArcProcessor.java:380)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:887)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)

Caused by: java.lang.RuntimeException:
io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#registerBeans threw an exception: java.lang.IllegalArgumentException: Producer method return type not found in index: org.springframework.boot.autoconfigure.web.servlet.WebMvcRegist
rations
        at io.quarkus.arc.processor.Types.getProducerMethodTypeClosure(Types.java:245)
        at io.quarkus.arc.processor.Beans.createProducerMethod(Beans.java:236)
        at io.quarkus.arc.processor.BeanDeployment.findBeans(BeanDeployment.java:1020)
        at io.quarkus.arc.processor.BeanDeployment.registerBeans(BeanDeployment.java:233)
        at io.quarkus.arc.processor.BeanProcessor.registerBeans(BeanProcessor.java:120)
        at io.quarkus.arc.deployment.ArcProcessor.registerBeans(ArcProcessor.java:380)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:887)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)

Caused by: io.quarkus.builder.BuildException:
Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#registerBeans threw an exception: java.lang.IllegalArgumentException: Producer method return type not found in index: org.springframework.boot.autoconfigure.web.servlet.WebMvcRegist
rations
        at io.quarkus.arc.processor.Types.getProducerMethodTypeClosure(Types.java:245)
        at io.quarkus.arc.processor.Beans.createProducerMethod(Beans.java:236)
        at io.quarkus.arc.processor.BeanDeployment.findBeans(BeanDeployment.java:1020)
        at io.quarkus.arc.processor.BeanDeployment.registerBeans(BeanDeployment.java:233)
        at io.quarkus.arc.processor.BeanProcessor.registerBeans(BeanProcessor.java:120)
        at io.quarkus.arc.deployment.ArcProcessor.registerBeans(ArcProcessor.java:380)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:887)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)

Caused by: java.lang.IllegalArgumentException: Producer method return type not found in index: org.springframework.boot.autoconfigure.web.servlet.WebMvcRegistrations

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors: 
[ERROR]   ExampleResourceTest.testHelloEndpoint » Runtime java.lang.RuntimeException: io...
[INFO]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  17.036 s
[INFO] Finished at: 2022-02-20T17:53:05+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project base-starter-flow-quarkus: There are test failures.
[ERROR]
[ERROR] Please refer to C:\local\work\clienti\shadow-ufficiodiscount\code\-tests\live-view\base-starter-flow-quarkus\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
~~~

# How to reproduce
In order to reproduce just add the `quarkus-spring-data-jpa` dependency.
~~~
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-spring-data-jpa</artifactId>
        </dependency>
~~~

Thanks

**Comment by lamemind-ud** [comment]
Hello @mstahv and thanks for you response, but it's not a datasource related problem.

I'm not extending Panache, I'm using base entities
~~~
@Entity
@Table(name = "Brand")
public class Brand {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    private Integer id;
[..]
~~~

I have recreated the issue with the following steps
- clone the repo
- add dependencies
  - quarkus-hibernate-orm
  - quarkus-spring-data-jpa
  - quarkus-jdbc-h2
  - quarkus-junit5 scope test (follow me and add test dependency too)
- add an `@Entity`, say `org.demo.Brand`
- add related repository `org.demo.BrandRepository`
- add a unit test and persist a new entity
- add datasource as follow

~~~
quarkus.hibernate-orm.packages=org.demo

quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.password=password
quarkus.datasource.jdbc.url=jdbc:h2:mem:quarkus_test;DB_CLOSE_DELAY=-1
quarkus.hibernate-orm.database.generation=create
quarkus.hibernate-orm.log.sql=true
~~~

- now run `mwnv`

**Expected result**: it should work
**Result**: The test Fails with the stack trace reported in my previous comment

Idk if it's useful, but if you remove `vaadin-core-jandex` dependency, the test works. And of course it crashes when you load `localhost:8080` and this is expected to crash.

Thanks again

**Comment by mstahv** [comment]
Sounds weird. Maybe there is something extra in the vaadin-core-jandex that should not be there 🤔

Could you share that project somehow? zip it and attach it to this issue, or share it in GitHub. That would really help our core team to look into it (and this way increase the chances that they would look into it sooner).

**Comment by lamemind-ud** [comment]
> Sounds weird. Maybe there is something extra in the vaadin-core-jandex that should not be there 🤔
> 
> Could you share that project somehow? zip it and attach it to this issue, or share it in GitHub. That would really help our core team to look into it (and this way increase the chances that they would look into it sooner).

@mstahv I'll share the full project tomorrow
