### ISSUE TITLE
Undertow NoClassDefFoundError

### ISSUE THREAD

**Issue by Dudeplayz** [vaadin/base-starter-flow-quarkus#7]
Hi,
I cloned this repository and tried to start the app with the mentioned `mvn clean package quarkus:dev`. But it fails with a NoClassDefFoundError. The complete log is below:

```
HOTSWAP AGENT: 23:16:09.685 INFO (org.hotswap.agent.HotswapAgent) - Loading Hotswap agent {1.4.1} - unlimited runtime class redefinition.
HOTSWAP AGENT: 23:16:09.861 INFO (org.hotswap.agent.config.PluginRegistry) - Discovered plugins: [JdkPlugin, Hotswapper, WatchResources, ClassInitPlugin, AnonymousClassPatch, Hibernate, Hibernate3JPA, Hibernate3, Spring, Jersey1, Jersey2, Jetty, Tomcat, ZK, Logback, Log4j2, MyFaces, Mojarra, Omnifaces, ELResolver, WildFlyELResolver, OsgiEquinox, Owb, Proxy, WebObjects, Weld, JBossModules, ResteasyRegistry, Deltaspike, GlassFish, Vaadin, Wicket, CxfJAXRS, FreeMarker, Undertow, MyBatis]
Starting HotswapAgent 'C:\DEV\JDK\dcevm-11.0.8+1\lib\hotswap\hotswap-agent.jar'
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------< org.acme:base-starter-flow-quarkus >-----------------
[INFO] Building base-starter-flow-quarkus 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- quarkus-maven-plugin:2.2.2.Final:dev (default-cli) @ base-starter-flow-quarkus ---
[INFO] Invoking io.quarkus:quarkus-maven-plugin:2.2.2.Final:generate-code @ base-starter-flow-quarkus
[INFO] Invoking org.apache.maven.plugins:maven-resources-plugin:2.6:resources @ base-starter-flow-quarkus
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Invoking org.apache.maven.plugins:maven-compiler-plugin:3.1:compile @ base-starter-flow-quarkus
[INFO] Nothing to compile - all classes are up to date
[INFO] Invoking org.apache.maven.plugins:maven-resources-plugin:2.6:testResources @ base-starter-flow-quarkus
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\DEV\IdeaProjects\base-starter-flow-quarkus\src\test\resources
[INFO] Invoking org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile @ base-starter-flow-quarkus
[INFO] No sources to compile
Starting HotswapAgent 'C:\DEV\JDK\dcevm-11.0.8+1\lib\hotswap\hotswap-agent.jar'
Listening for transport dt_socket at address: 5005
HOTSWAP AGENT: 23:16:17.420 INFO (org.hotswap.agent.HotswapAgent) - Loading Hotswap agent {1.4.1} - unlimited runtime class redefinition.
HOTSWAP AGENT: 23:16:17.571 INFO (org.hotswap.agent.config.PluginRegistry) - Discovered plugins: [JdkPlugin, Hotswapper, WatchResources, ClassInitPlugin, AnonymousClassPatch, Hibernate, Hibernate3JPA, Hibernate3, Spring, Jersey1, Jersey2, Jetty, Tomcat, ZK, Logback, Log4j2, MyFaces, Mojarra, Omnifaces, ELResolver, WildFlyELResolver, OsgiEquinox, Owb, Proxy, WebObjects, Weld, JBossModules, ResteasyRegistry, Deltaspike, GlassFish, Vaadin, Wicket, CxfJAXRS, FreeMarker, Undertow, MyBatis]
Press [h] for more options>
Tests paused
Press [r] to resume testing, [h] for more options>
Press [r] to resume testing, [o] Toggle test output, [h] for more options>
HOTSWAP AGENT: 23:16:19.081 INFO (org.hotswap.agent.plugin.vaadin.VaadinPlugin) - Initialized Vaadin plugin
HOTSWAP AGENT: 23:16:21.054 INFO (org.hotswap.agent.plugin.vaadin.VaadinPlugin) - Initialized Vaadin plugin
2021-10-05 23:16:21,176 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2021-10-05 23:16:21,177 ERROR [io.qua.run.boo.StartupActionImpl] (Quarkus Main Thread) Error running Quarkus: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:98)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:65)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	... 6 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:247)
	... 15 more
Caused by: java.lang.NoClassDefFoundError: io/undertow/server/handlers/resource/ResourceChangeListener
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
	at java.base/java.lang.Class.getMethodsRecursive(Class.java:3307)
	at java.base/java.lang.Class.getMethod0(Class.java:3293)
	at java.base/java.lang.Class.getMethod(Class.java:2106)
	at org.hotswap.agent.util.ReflectionHelper.invoke(ReflectionHelper.java:51)
	at org.hotswap.agent.plugin.undertow.UndertowPlugin.init(UndertowPlugin.java:78)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java)
	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder.bootServletContainer(UndertowDeploymentRecorder.java:519)
	at io.quarkus.deployment.steps.UndertowBuildStep$build-649634386.deploy_0(UndertowBuildStep$build-649634386.zig:2502)
	at io.quarkus.deployment.steps.UndertowBuildStep$build-649634386.deploy(UndertowBuildStep$build-649634386.zig:40)
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:227)
	... 15 more
Caused by: java.lang.ClassNotFoundException: io.undertow.server.handlers.resource.ResourceChangeListener
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:455)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:405)
	... 27 more

2021-10-05 23:16:21,227 INFO  [org.jbo.threads] (main) JBoss Threads version 3.4.2.Final

```

**Comment by Dudeplayz** [comment]
After deeper looking at the stack trace, I saw that there seems to be an issue if the hotswapagent is used as runtime. So I now used Adoptium 11 and everything works. I will keep the issue open in case further investigations are needed.

**Comment by mshabarov** [comment]
Looks like a mismatch/incompatibility between HotSwap agent and Undertow. I close the issue because I don't see what we can do on the Vaadin side.
